### ISSUE TITLE
Umbrella Alpine Wsl2 and Docker-For-Win

### ISSUE THREAD

**Issue by airtonix** [agowa338/WSL-DistroLauncher-Alpine#26]
Recently affected by a fatal bug released in a Window Insiders and Docker Desktop Edge caused me to react by wiping my prevous Alpine WSL setup and reinstalling.

Upon reinstall, I had to revisit a few of the problems getting docker-for-win and alpine wsl2 working properly.

Starting some notes here:

- [x] [Windows Insiders 20226 breaks networking for WSL2](https://github.com/microsoft/WSL/issues/5821#issuecomment-704784252), reported in this repo as #25 
- [x] ~~Can't install docker because glibc vs musl https://github.com/sgerrand/alpine-pkg-glibc~~ don't do this anymore
- [x] can't run docker-compose because libz.so.1 doesn't like something about `/tmp`: #27

**Comment by airtonix** [comment]
solvedall my issues so far I think
